### ISSUE TITLE
Use express for routing

### ISSUE THREAD

**Issue by duvholt** [appKom/notiwire2#1]
We should consider using [express](https://www.npmjs.org/package/express). 

This is mainly because we don't have any simple way to support /office/<affiliation>/ etc atm now. 

It seems pretty simple to use.  http://expressjs.com/starter/basic-routing.html

**Comment by vikre** [comment]
@cXhristian You really should, its quite simple and nice.

**Comment by Jimtrim** [comment]
I endorse Express, getting the interface app.HTTP_VERB("/path/", function(){...}) is just awesomely simple.

**Comment by duvholt** [comment]
Express is in use so I'm closing this!
