### ISSUE TITLE
New Abakus coffee url

### ISSUE THREAD

**Issue by draperunner** [appKom/notiwire2#10]
The Abakus coffee API is now on HTTPS. The correct url is `https://kaffe.abakus.no/coffee.txt`

**Comment by michaeljohansen** [comment]
Thanks @draperunner.
@duvholt Would be great if you could do the edit and redeploy?

**Comment by duvholt** [comment]
Yep, I'll do it. Planning a few changes which I will hopefully have time for in the coming days.

For the moment I think the API still works? HTTP redirects to HTTPS.

**Comment by michaeljohansen** [comment]
Good. Let me know if you want me to make any corresponding changes in Notifier or Notiwall.

**Comment by duvholt** [comment]
This was fixed a few days ago. :)
